version: "3"

services:
  nginx:
    ports:
      - "80:80"

  node-app:
    build:
      context: .
      args:
        - NODE_ENV=prod
    environment:
      - NODE_ENV=prod
      - MONGO_USER=root
      - MONGO_PASSWORD=admin
      - SESSION_SECRET=secret

    command: npm start

  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=admin
